spring.application.name=blog
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#The spring.jpa.hibernate.ddl-auto=update setting enables Hibernate to automatically
# update the database schema based on our entity classes.
#The show-sql and format_sql properties help during development by logging SQL statements to the console.